// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using MudBlazorWASM.Server;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MudBlazorWASM.Server.Data
{
    public partial class SchooldbContext
    {
        private SchooldbContextProcedures _procedures;

        public virtual SchooldbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new SchooldbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public SchooldbContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public interface ISchooldbContextProcedures
    {
    }

    public partial class SchooldbContextProcedures : ISchooldbContextProcedures
    {
        private readonly SchooldbContext _context;

        public SchooldbContextProcedures(SchooldbContext context)
        {
            _context = context;
        }
    }
}
