// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using MudBlazorWASM.Server;

namespace MudBlazorWASM.Server.Data
{
    public partial class SchooldbContext : DbContext
    {
        public SchooldbContext(DbContextOptions<SchooldbContext> options)
            : base(options)
        {
        }
        public virtual DbSet<Admission> Admissions {get; set; } = null!;
        public virtual DbSet<Classroom> Classrooms { get; set; } = null!;
        public virtual DbSet<Department> Departments { get; set; } = null!;
        public virtual DbSet<Employee> Employees { get; set; } = null!;
        public virtual DbSet<Schedule> Schedules { get; set; } = null!;
        public virtual DbSet<Student> Students { get; set; } = null!;
        public virtual DbSet<Subject> Subjects { get; set; } = null!;
        public virtual DbSet<SubjectOffering> SubjectOfferings { get; set; } = null!;
        public virtual DbSet<SubmittedGrade> SubmittedGrades { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Classroom>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Bldgcode)
                    .HasMaxLength(50)
                    .HasColumnName("BLDGCODE");

                entity.Property(e => e.Bldgname)
                    .HasMaxLength(50)
                    .HasColumnName("BLDGNAME");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .HasColumnName("NAME");

                entity.Property(e => e.Roomno)
                    .HasMaxLength(50)
                    .HasColumnName("ROOMNO");

                entity.Property(e => e.Type)
                    .HasMaxLength(50)
                    .HasColumnName("TYPE");
            });

            modelBuilder.Entity<Department>(entity =>
            {
                entity.HasKey(e => e.Deptno);

                entity.Property(e => e.Deptno)
                    .ValueGeneratedNever()
                    .HasColumnName("DEPTNO");

                entity.Property(e => e.Abbreviations)
                    .HasMaxLength(50)
                    .HasColumnName("ABBREVIATIONS");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .HasColumnName("DESCRIPTION");

                entity.Property(e => e.Type)
                    .HasMaxLength(1)
                    .HasColumnName("TYPE");
            });

            modelBuilder.Entity<Employee>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Address1)
                    .HasMaxLength(100)
                    .HasColumnName("ADDRESS1");

                entity.Property(e => e.Address2)
                    .HasMaxLength(50)
                    .HasColumnName("ADDRESS2");

                entity.Property(e => e.Completename)
                    .HasMaxLength(50)
                    .HasColumnName("COMPLETENAME");

                entity.Property(e => e.Department)
                    .HasMaxLength(50)
                    .HasColumnName("DEPARTMENT");

                entity.Property(e => e.Firstname)
                    .HasMaxLength(50)
                    .HasColumnName("FIRSTNAME");

                entity.Property(e => e.Idno)
                    .HasMaxLength(50)
                    .HasColumnName("IDNO");

                entity.Property(e => e.Lastname)
                    .HasMaxLength(50)
                    .HasColumnName("LASTNAME");

                entity.Property(e => e.Mi)
                    .HasMaxLength(50)
                    .HasColumnName("MI");

                entity.Property(e => e.Position)
                    .HasMaxLength(50)
                    .HasColumnName("POSITION");
            });

            modelBuilder.Entity<Schedule>(entity =>
            {
                entity.HasKey(e => e.Schedid);

                entity.Property(e => e.Schedid)
                    .ValueGeneratedNever()
                    .HasColumnName("SCHEDID");

                entity.Property(e => e.Days)
                    .HasMaxLength(50)
                    .HasColumnName("DAYS");

                entity.Property(e => e.Etime).HasColumnName("ETIME");

                entity.Property(e => e.Offerno).HasColumnName("OFFERNO");

                entity.Property(e => e.Session)
                    .HasMaxLength(50)
                    .HasColumnName("SESSION");

                entity.Property(e => e.Stime).HasColumnName("STIME");

                entity.Property(e => e.Subjcode)
                    .HasMaxLength(50)
                    .HasColumnName("SUBJCODE");

                entity.Property(e => e.Teachid).HasColumnName("TEACHID");

                entity.Property(e => e.Type)
                    .HasMaxLength(50)
                    .HasColumnName("TYPE");
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.HasKey(e => e.Studno);

                entity.Property(e => e.Studno)
                    .ValueGeneratedNever()
                    .HasColumnName("STUDNO");

                entity.Property(e => e.Awardno)
                    .HasMaxLength(1)
                    .HasColumnName("AWARDNO");

                entity.Property(e => e.Claimno)
                    .HasMaxLength(1)
                    .HasColumnName("CLAIMNO");

                entity.Property(e => e.Creditno)
                    .HasMaxLength(1)
                    .HasColumnName("CREDITNO");

                entity.Property(e => e.Deptno)
                    .HasMaxLength(1)
                    .HasColumnName("DEPTNO");

                entity.Property(e => e.Firstname)
                    .HasMaxLength(50)
                    .HasColumnName("FIRSTNAME");

                entity.Property(e => e.Gender)
                    .HasMaxLength(1)
                    .HasColumnName("GENDER");

                entity.Property(e => e.Grantno)
                    .HasMaxLength(1)
                    .HasColumnName("GRANTNO");

                entity.Property(e => e.Lastname)
                    .HasMaxLength(50)
                    .HasColumnName("LASTNAME");

                entity.Property(e => e.Mi)
                    .HasMaxLength(50)
                    .HasColumnName("MI");

                entity.Property(e => e.Ptag)
                    .HasMaxLength(1)
                    .HasColumnName("PTAG");

                entity.Property(e => e.Region)
                    .HasMaxLength(1)
                    .HasColumnName("REGION");

                entity.Property(e => e.Relikgion)
                    .HasMaxLength(1)
                    .HasColumnName("RELIKGION");

                entity.Property(e => e.Schacct)
                    .HasMaxLength(1)
                    .HasColumnName("SCHACCT");

                entity.Property(e => e.Schadd)
                    .HasMaxLength(1)
                    .HasColumnName("SCHADD");

                entity.Property(e => e.Schapp)
                    .HasMaxLength(1)
                    .HasColumnName("SCHAPP");

                entity.Property(e => e.Schcode)
                    .HasMaxLength(1)
                    .HasColumnName("SCHCODE");

                entity.Property(e => e.Schgrant)
                    .HasMaxLength(1)
                    .HasColumnName("SCHGRANT");

                entity.Property(e => e.Scholar)
                    .HasMaxLength(1)
                    .HasColumnName("SCHOLAR");

                entity.Property(e => e.Schvet)
                    .HasMaxLength(1)
                    .HasColumnName("SCHVET");

                entity.Property(e => e.Slotno)
                    .HasMaxLength(1)
                    .HasColumnName("SLOTNO");

                entity.Property(e => e.Status)
                    .HasMaxLength(1)
                    .HasColumnName("STATUS");
            });

            modelBuilder.Entity<Subject>(entity =>
            {
                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("ID");

                entity.Property(e => e.Category)
                    .HasMaxLength(1)
                    .HasColumnName("CATEGORY");

                entity.Property(e => e.Coursecode)
                    .HasMaxLength(50)
                    .HasColumnName("COURSECODE");

                entity.Property(e => e.Coursedesc)
                    .HasMaxLength(100)
                    .HasColumnName("COURSEDESC");

                entity.Property(e => e.Courseno)
                    .HasMaxLength(50)
                    .HasColumnName("COURSENO");

                entity.Property(e => e.Deptno)
                    .HasMaxLength(50)
                    .HasColumnName("DEPTNO");

                entity.Property(e => e.Lab)
                    .HasMaxLength(50)
                    .HasColumnName("LAB");

                entity.Property(e => e.Lec).HasColumnName("LEC");

                entity.Property(e => e.Prereq)
                    .HasMaxLength(50)
                    .HasColumnName("PREREQ");

                entity.Property(e => e.Semcode)
                    .HasMaxLength(50)
                    .HasColumnName("SEMCODE");

                entity.Property(e => e.Semester)
                    .HasMaxLength(50)
                    .HasColumnName("SEMESTER");

                entity.Property(e => e.Status)
                    .HasMaxLength(50)
                    .HasColumnName("STATUS");

                entity.Property(e => e.Tyype)
                    .HasMaxLength(50)
                    .HasColumnName("TYYPE");

                entity.Property(e => e.Units).HasColumnName("UNITS");

                entity.Property(e => e.Yrlevel)
                    .HasMaxLength(50)
                    .HasColumnName("YRLEVEL");
            });

            modelBuilder.Entity<SubjectOffering>(entity =>
            {
                entity.HasKey(e => e.OfferNo);

                entity.ToTable("SubjectOffering");

                entity.Property(e => e.OfferNo)
                    .ValueGeneratedNever()
                    .HasColumnName("OFFER_NO");

                entity.Property(e => e.Days)
                    .HasMaxLength(50)
                    .HasColumnName("DAYS");

                entity.Property(e => e.Deptno).HasColumnName("DEPTNO");

                entity.Property(e => e.Lab).HasColumnName("LAB");

                entity.Property(e => e.Lec).HasColumnName("LEC");

                entity.Property(e => e.Roomno)
                    .HasMaxLength(1)
                    .HasColumnName("ROOMNO");

                entity.Property(e => e.Secno)
                    .HasMaxLength(1)
                    .HasColumnName("SECNO");

                entity.Property(e => e.Semcode)
                    .HasMaxLength(1)
                    .HasColumnName("SEMCODE");

                entity.Property(e => e.Subjcode)
                    .HasMaxLength(50)
                    .HasColumnName("SUBJCODE");

                entity.Property(e => e.Subjdesc)
                    .HasMaxLength(100)
                    .HasColumnName("SUBJDESC");

                entity.Property(e => e.Syr)
                    .HasMaxLength(1)
                    .HasColumnName("SYR");

                entity.Property(e => e.Teachid).HasColumnName("TEACHID");

                entity.Property(e => e.Time)
                    .HasColumnType("datetime")
                    .HasColumnName("TIME");

                entity.Property(e => e.Units).HasColumnName("UNITS");
            });

            modelBuilder.Entity<SubmittedGrade>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Average).HasColumnName("AVERAGE");

                entity.Property(e => e.Date)
                    .HasColumnType("date")
                    .HasColumnName("DATE");

                entity.Property(e => e.Deptno).HasColumnName("DEPTNO");

                entity.Property(e => e.Final).HasColumnName("FINAL");

                entity.Property(e => e.Firstname)
                    .HasMaxLength(50)
                    .HasColumnName("FIRSTNAME");

                entity.Property(e => e.Lastname)
                    .HasMaxLength(50)
                    .HasColumnName("LASTNAME");

                entity.Property(e => e.Mi)
                    .HasMaxLength(50)
                    .HasColumnName("MI");

                entity.Property(e => e.Midterm).HasColumnName("MIDTERM");

                entity.Property(e => e.Offerno).HasColumnName("OFFERNO");

                entity.Property(e => e.Prefinal).HasColumnName("PREFINAL");

                entity.Property(e => e.Prelim).HasColumnName("PRELIM");

                entity.Property(e => e.Retake)
                    .HasMaxLength(50)
                    .HasColumnName("RETAKE");

                entity.Property(e => e.Semester).HasColumnName("SEMESTER");

                entity.Property(e => e.Studno).HasColumnName("STUDNO");

                entity.Property(e => e.Subjcode)
                    .HasMaxLength(50)
                    .HasColumnName("SUBJCODE");

                entity.Property(e => e.Subjdesc)
                    .HasMaxLength(50)
                    .HasColumnName("SUBJDESC");

                entity.Property(e => e.Syr).HasColumnName("SYR");

                entity.Property(e => e.Teachid).HasColumnName("TEACHID");

                entity.Property(e => e.Time).HasColumnName("TIME");

                entity.Property(e => e.Units).HasColumnName("UNITS");

                entity.Property(e => e.Yrlevel).HasColumnName("YRLEVEL");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingGeneratedFunctions(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}