// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MudBlazorWASM.Shared.Models
{
    public partial class Admission
    {
        [Key]
        [Column("EnrID")]
        public int EnrId { get; set; }
        public int? Studno { get; set; }
        [StringLength(50)]
        public string? Lastname { get; set; }
        [StringLength(50)]
        public string? Firstname { get; set; }
        public int? OfferNo { get; set; }
        [StringLength(50)]
        public string? SubjCode { get; set; }
        [StringLength(50)]
        public string? SubjDesc { get; set; }

        [ForeignKey("OfferNo")]
        [InverseProperty("Admissions")]
        public virtual SubjectOffering? OfferNoNavigation { get; set; }
        [ForeignKey("Studno")]
        [InverseProperty("Admissions")]
        public virtual Student? StudnoNavigation { get; set; }
    }
}