// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MudBlazorWASM.Shared.Models
{
    public partial class Classroom
    {
        [Column("ROOMCOUNT")]
        public int Roomcount { get; set; }
        [Key]
        [Column("ROOMNO")]
        [StringLength(50)]
        public string Roomno { get; set; } = null!;
        [Column("NAME")]
        [StringLength(50)]
        public string? Name { get; set; }
        [Column("BLDGCODE")]
        [StringLength(50)]
        public string? Bldgcode { get; set; }
        [Column("BLDGNAME")]
        [StringLength(50)]
        public string? Bldgname { get; set; }
        [Column("TYPE")]
        [StringLength(50)]
        public string? Type { get; set; }
    }
}