// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MudBlazorWASM.Shared.Models
{
    [Keyless]
    public partial class Classroom
    {
        [Column("ROOMNO")]
        [StringLength(50)]
        public string Roomno { get; set; } = null!;
        [Column("NAME")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("BLDGCODE")]
        [StringLength(50)]
        public string Bldgcode { get; set; } = null!;
        [Column("BLDGNAME")]
        [StringLength(50)]
        public string Bldgname { get; set; } = null!;
        [Column("TYPE")]
        [StringLength(50)]
        public string Type { get; set; } = null!;
    }
}