// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MudBlazorWASM.Shared.Models
{
    public partial class Department
    {
        [Column("DEPTCOUNT")]
        public int Deptcount { get; set; }
        [Key]
        [Column("DEPTNO")]
        public int Deptno { get; set; }
        [Column("ABBREVIATIONS")]
        [StringLength(50)]
        public string? Abbreviations { get; set; }
        [Column("DESCRIPTION", TypeName = "ntext")]
        public string? Description { get; set; }
        [Column("TYPE")]
        [StringLength(50)]
        public string? Type { get; set; }
    }
}