// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MudBlazorWASM.Shared.Models
{
    public partial class Department
    {
        [Key]
        [Column("DEPTNO")]
        public int Deptno { get; set; }
        [Column("ABBREVIATIONS")]
        [StringLength(50)]
        public string? Abbreviations { get; set; }
        [Column("DESCRIPTION")]
        [StringLength(50)]
        public string? Description { get; set; }
        [Column("TYPE")]
        [StringLength(1)]
        public string? Type { get; set; }
    }
}