// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MudBlazorWASM.Shared.Models
{
    [Keyless]
    public partial class Employee
    {
        [Column("IDNO")]
        public int? Idno { get; set; }
        [Column("COMPLETENAME")]
        [StringLength(50)]
        public string? Completename { get; set; }
        [Column("LASTNAME")]
        [StringLength(50)]
        public string? Lastname { get; set; }
        [Column("FIRSTNAME")]
        [StringLength(50)]
        public string? Firstname { get; set; }
        [Column("MI")]
        [StringLength(50)]
        public string? Mi { get; set; }
        [Column("ADDRESS1")]
        [StringLength(100)]
        public string? Address1 { get; set; }
        [Column("ADDRESS2")]
        [StringLength(50)]
        public string? Address2 { get; set; }
        [Column("POSITION")]
        [StringLength(50)]
        public string? Position { get; set; }
        [Column("DEPARTMENT")]
        [StringLength(50)]
        public string? Department { get; set; }
    }
}