// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MudBlazorWASM.Shared.Models
{
    [Index("CourseId", Name = "IX_Enrollments_CourseID")]
    [Index("StudentId", Name = "IX_Enrollments_StudentID")]
    public partial class Enrollment
    {
        [Key]
        public int CountId { get; set; }
        [Column("EnrollmentID")]
        public int EnrollmentId { get; set; }
        [Column("CourseID")]
        public int CourseId { get; set; }
        [Column("StudentID")]
        public int StudentId { get; set; }
        public int? Grade { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("Enrollments")]
        public virtual Course Course { get; set; }
        [ForeignKey("StudentId")]
        [InverseProperty("Enrollments")]
        public virtual Student Student { get; set; }
    }
}