// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MudBlazorWASM.Shared.Models
{
    public partial class GradeSummary
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("DEPTNO")]
        [StringLength(50)]
        public string Deptno { get; set; }
        [Column("OFFERNO")]
        [StringLength(50)]
        public string Offerno { get; set; }
        [Column("COURSENO")]
        [StringLength(50)]
        public string Courseno { get; set; }
        [Column("STUDNO")]
        [StringLength(50)]
        public string Studno { get; set; }
        [Column("LASTNAME")]
        [StringLength(50)]
        public string Lastname { get; set; }
        [Column("FIRSTNAME")]
        [StringLength(50)]
        public string Firstname { get; set; }
        [Column("MI")]
        [StringLength(50)]
        public string Mi { get; set; }
        [Column("PRE")]
        public double? Pre { get; set; }
        [Column("MID")]
        public double? Mid { get; set; }
        [Column("SEMI")]
        public double? Semi { get; set; }
        [Column("FINAL")]
        public double? Final { get; set; }
        [Column("AVERAGE")]
        public double? Average { get; set; }
        [Column("SUBJECTDESC")]
        [StringLength(100)]
        public string Subjectdesc { get; set; }
    }
}