// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MudBlazorWASM.Shared.Models
{
    public partial class Instructor
    {
        public Instructor()
        {
            Courses = new HashSet<Course>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        public DateTime HireDate { get; set; }
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }

        [InverseProperty("Instructor")]
        public virtual RoomAssignment RoomAssignment { get; set; }
        [InverseProperty("Instructor")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}