// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MudBlazorWASM.Shared.Models
{
    public partial class OfferedSubject
    {
        [Column("COUNTID")]
        public int Countid { get; set; }
        [Column("DEPTNO")]
        public short? Deptno { get; set; }
        [Key]
        [Column("OFFER_NO")]
        public int OfferNo { get; set; }
        [Column("SUBJCODE")]
        [StringLength(50)]
        public string? Subjcode { get; set; }
        [Column("SUBJDESC")]
        [StringLength(100)]
        public string? Subjdesc { get; set; }
        [Column("TIME")]
        [StringLength(1)]
        public string? Time { get; set; }
        [Column("DAYS")]
        [StringLength(1)]
        public string? Days { get; set; }
        [Column("LAB")]
        [StringLength(1)]
        public string? Lab { get; set; }
        [Column("LEC")]
        [StringLength(1)]
        public string? Lec { get; set; }
        [Column("UNITS")]
        [StringLength(1)]
        public string? Units { get; set; }
        [Column("TEACHID")]
        [StringLength(1)]
        public string? Teachid { get; set; }
        [Column("ROOMNO")]
        [StringLength(1)]
        public string? Roomno { get; set; }
        [Column("SECNO")]
        [StringLength(1)]
        public string? Secno { get; set; }
        [Column("SEMCODE")]
        [StringLength(1)]
        public string? Semcode { get; set; }
        [Column("SYR")]
        [StringLength(1)]
        public string? Syr { get; set; }
    }
}