// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
<<<<<<< Updated upstream
#nullable disable
=======
#nullable enable
>>>>>>> Stashed changes
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MudBlazorWASM.Shared.Models
{
    public partial class Student
    {
        public Student()
        {
<<<<<<< Updated upstream
            Enrollments = new HashSet<Enrollment>();
        }

        [Key]
        public int Id { get; set; }
        [Column("StudID")]
        public int StudId { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Mi { get; set; }
        public DateTime EnrollmentDate { get; set; }

        [InverseProperty("Student")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
=======
            Admissions = new HashSet<Admission>();
        }

        [Key]
        [Column("STUDNO")]
        public int Studno { get; set; }
        [Column("LASTNAME")]
        [StringLength(50)]
        public string? Lastname { get; set; }
        [Column("FIRSTNAME")]
        [StringLength(50)]
        public string? Firstname { get; set; }
        [Column("MI")]
        [StringLength(50)]
        public string? Mi { get; set; }
        [Column("DEPTNO")]
        [StringLength(1)]
        public string? Deptno { get; set; }
        [Column("GENDER")]
        [StringLength(1)]
        public string? Gender { get; set; }
        [Column("RELIKGION")]
        [StringLength(1)]
        public string? Relikgion { get; set; }
        [Column("SCHOLAR")]
        [StringLength(1)]
        public string? Scholar { get; set; }
        [Column("SCHCODE")]
        [StringLength(1)]
        public string? Schcode { get; set; }
        [Column("AWARDNO")]
        [StringLength(1)]
        public string? Awardno { get; set; }
        [Column("SLOTNO")]
        [StringLength(1)]
        public string? Slotno { get; set; }
        [Column("CLAIMNO")]
        [StringLength(1)]
        public string? Claimno { get; set; }
        [Column("CREDITNO")]
        [StringLength(1)]
        public string? Creditno { get; set; }
        [Column("GRANTNO")]
        [StringLength(1)]
        public string? Grantno { get; set; }
        [Column("SCHGRANT")]
        [StringLength(1)]
        public string? Schgrant { get; set; }
        [Column("SCHAPP")]
        [StringLength(1)]
        public string? Schapp { get; set; }
        [Column("REGION")]
        [StringLength(1)]
        public string? Region { get; set; }
        [Column("SCHACCT")]
        [StringLength(1)]
        public string? Schacct { get; set; }
        [Column("SCHADD")]
        [StringLength(1)]
        public string? Schadd { get; set; }
        [Column("SCHVET")]
        [StringLength(1)]
        public string? Schvet { get; set; }
        [Column("STATUS")]
        [StringLength(1)]
        public string? Status { get; set; }
        [Column("PTAG")]
        [StringLength(1)]
        public string? Ptag { get; set; }

        [InverseProperty("StudnoNavigation")]
        public virtual ICollection<Admission> Admissions { get; set; }
>>>>>>> Stashed changes
    }
}