// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MudBlazorWASM.Shared.Models
{
    public partial class Student
    {
        public Student()
        {
            Enrollments = new HashSet<Enrollment>();
        }

        [Key]
        public int Id { get; set; }
        [Column("StudID")]
        public int StudId { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Mi { get; set; }
        public DateTime EnrollmentDate { get; set; }

        [InverseProperty("Student")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}