// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MudBlazorWASM.Shared.Models
{
    [Table("SubjectOffering")]
    public partial class SubjectOffering
    {
        public SubjectOffering()
        {
            Admissions = new HashSet<Admission>();
        }

        [Column("DEPTNO")]
        public int? Deptno { get; set; }
        [Key]
        [Column("OFFER_NO")]
        public int OfferNo { get; set; }
        [Column("SUBJCODE")]
        [StringLength(50)]
        public string? Subjcode { get; set; }
        [Column("SUBJDESC")]
        [StringLength(100)]
        public string? Subjdesc { get; set; }
        [Column("TIME", TypeName = "datetime")]
        public DateTime? Time { get; set; }
        [Column("DAYS")]
        [StringLength(50)]
        public string? Days { get; set; }
        [Column("LAB")]
        public int? Lab { get; set; }
        [Column("LEC")]
        public int? Lec { get; set; }
        [Column("UNITS")]
        public int? Units { get; set; }
        [Column("TEACHID")]
        public int? Teachid { get; set; }
        [Column("ROOMNO")]
        [StringLength(1)]
        public string? Roomno { get; set; }
        [Column("SECNO")]
        [StringLength(1)]
        public string? Secno { get; set; }
        [Column("SEMCODE")]
        [StringLength(1)]
        public string? Semcode { get; set; }
        [Column("SYR")]
        [StringLength(1)]
        public string? Syr { get; set; }

        [InverseProperty("OfferNoNavigation")]
        public virtual ICollection<Admission> Admissions { get; set; }
    }
}