// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MudBlazorWASM.Shared.Models
{
    public partial class Subject
    {
        [Column("COURSECODE")]
        [StringLength(50)]
        public string? Coursecode { get; set; }
        [Column("COURSEDESC")]
        [StringLength(100)]
        public string? Coursedesc { get; set; }
        [Column("LAB")]
        [StringLength(50)]
        public string? Lab { get; set; }
        [Column("LEC")]
        public int? Lec { get; set; }
        [Column("UNITS")]
        public int? Units { get; set; }
        [Column("CATEGORY")]
        [StringLength(1)]
        public string? Category { get; set; }
        [Column("STATUS")]
        [StringLength(50)]
        public string? Status { get; set; }
        [Column("PREREQ")]
        [StringLength(50)]
        public string? Prereq { get; set; }
        [Column("DEPTNO")]
        [StringLength(50)]
        public string? Deptno { get; set; }
        [Column("SEMESTER")]
        [StringLength(50)]
        public string? Semester { get; set; }
        [Column("SEMCODE")]
        [StringLength(50)]
        public string? Semcode { get; set; }
        [Column("YRLEVEL")]
        [StringLength(50)]
        public string? Yrlevel { get; set; }
        [Column("COURSENO")]
        [StringLength(50)]
        public string? Courseno { get; set; }
        [Column("TYYPE")]
        [StringLength(50)]
        public string? Tyype { get; set; }
        [Key]
        [Column("ID")]
        public int Id { get; set; }
    }
}