// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MudBlazorWASM.Shared.Models
{
    public partial class SubmittedGrade
    {
        [Column("STUDNO")]
        public int? Studno { get; set; }
        [Column("LASTNAME")]
        [StringLength(50)]
        public string? Lastname { get; set; }
        [Column("FIRSTNAME")]
        [StringLength(50)]
        public string? Firstname { get; set; }
        [Column("MI")]
        [StringLength(50)]
        public string? Mi { get; set; }
        [Column("YRLEVEL")]
        public int? Yrlevel { get; set; }
        [Column("SEMESTER")]
        public int? Semester { get; set; }
        [Column("SYR")]
        public int? Syr { get; set; }
        [Column("OFFERNO")]
        public int? Offerno { get; set; }
        [Column("COURSECODE")]
        [StringLength(50)]
        public string? Coursecode { get; set; }
        [Column("COURSEDESC")]
        [StringLength(50)]
        public string? Coursedesc { get; set; }
        [Column("UNITS")]
        public int? Units { get; set; }
        [Column("DEPTNO")]
        public int? Deptno { get; set; }
        [Column("PRELIM")]
        public double? Prelim { get; set; }
        [Column("MIDTERM")]
        public double? Midterm { get; set; }
        [Column("PREFINAL")]
        public double? Prefinal { get; set; }
        [Column("FINAL")]
        public double? Final { get; set; }
        [Column("AVERAGE")]
        public TimeSpan? Average { get; set; }
        [Column("RETAKE")]
        [StringLength(50)]
        public string? Retake { get; set; }
        [Column("TEACHID")]
        public int? Teachid { get; set; }
        [Column("DATE", TypeName = "date")]
        public DateTime? Date { get; set; }
        [Column("TIME")]
        public TimeSpan? Time { get; set; }
        [Key]
        [Column("SUBMISSIONID")]
        public int Submissionid { get; set; }
    }
}