// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MudBlazorWASM.Server;
using MudBlazorWASM.Server.Data;
using System;
using System.Collections.Generic;

#nullable disable

namespace MudBlazorWASM.Server.Data.Configurations
{
    public partial class ClassroomConfiguration : IEntityTypeConfiguration<Classroom>
    {
        public void Configure(EntityTypeBuilder<Classroom> entity)
        {
            entity.HasKey(e => e.Roomno);

            entity.Property(e => e.Roomno)
                .HasMaxLength(50)
                .HasColumnName("ROOMNO");

            entity.Property(e => e.Bldgcode)
                .HasMaxLength(50)
                .HasColumnName("BLDGCODE");

            entity.Property(e => e.Bldgname)
                .HasMaxLength(50)
                .HasColumnName("BLDGNAME");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("NAME");

            entity.Property(e => e.Roomcount)
                .ValueGeneratedOnAdd()
                .HasColumnName("ROOMCOUNT");

            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("TYPE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Classroom> entity);
    }
}
