// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MudBlazorWASM.Server;
using MudBlazorWASM.Server.Data;
using System;
using System.Collections.Generic;

#nullable disable

namespace MudBlazorWASM.Server.Data.Configurations
{
    public partial class OfferedSubjectConfiguration : IEntityTypeConfiguration<OfferedSubject>
    {
        public void Configure(EntityTypeBuilder<OfferedSubject> entity)
        {
            entity.HasKey(e => e.OfferNo);

            entity.Property(e => e.OfferNo)
                .ValueGeneratedNever()
                .HasColumnName("OFFER_NO");

            entity.Property(e => e.Countid)
                .ValueGeneratedOnAdd()
                .HasColumnName("COUNTID");

            entity.Property(e => e.Days)
                .HasMaxLength(1)
                .HasColumnName("DAYS");

            entity.Property(e => e.Deptno).HasColumnName("DEPTNO");

            entity.Property(e => e.Lab)
                .HasMaxLength(1)
                .HasColumnName("LAB");

            entity.Property(e => e.Lec)
                .HasMaxLength(1)
                .HasColumnName("LEC");

            entity.Property(e => e.Roomno)
                .HasMaxLength(1)
                .HasColumnName("ROOMNO");

            entity.Property(e => e.Secno)
                .HasMaxLength(1)
                .HasColumnName("SECNO");

            entity.Property(e => e.Semcode)
                .HasMaxLength(1)
                .HasColumnName("SEMCODE");

            entity.Property(e => e.Subjcode)
                .HasMaxLength(50)
                .HasColumnName("SUBJCODE");

            entity.Property(e => e.Subjdesc)
                .HasMaxLength(100)
                .HasColumnName("SUBJDESC");

            entity.Property(e => e.Syr)
                .HasMaxLength(1)
                .HasColumnName("SYR");

            entity.Property(e => e.Teachid)
                .HasMaxLength(1)
                .HasColumnName("TEACHID");

            entity.Property(e => e.Time)
                .HasMaxLength(1)
                .HasColumnName("TIME");

            entity.Property(e => e.Units)
                .HasMaxLength(1)
                .HasColumnName("UNITS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OfferedSubject> entity);
    }
}
