// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MudBlazorWASM.Server;
using MudBlazorWASM.Server.Data;
using System;
using System.Collections.Generic;

#nullable disable

namespace MudBlazorWASM.Server.Data.Configurations
{
    public partial class SubmittedGradeConfiguration : IEntityTypeConfiguration<SubmittedGrade>
    {
        public void Configure(EntityTypeBuilder<SubmittedGrade> entity)
        {
            entity.HasKey(e => e.Submissionid);

            entity.Property(e => e.Submissionid).HasColumnName("SUBMISSIONID");

            entity.Property(e => e.Average).HasColumnName("AVERAGE");

            entity.Property(e => e.Coursecode)
                .HasMaxLength(50)
                .HasColumnName("COURSECODE");

            entity.Property(e => e.Coursedesc)
                .HasMaxLength(50)
                .HasColumnName("COURSEDESC");

            entity.Property(e => e.Date)
                .HasColumnType("date")
                .HasColumnName("DATE");

            entity.Property(e => e.Deptno).HasColumnName("DEPTNO");

            entity.Property(e => e.Final).HasColumnName("FINAL");

            entity.Property(e => e.Firstname)
                .HasMaxLength(50)
                .HasColumnName("FIRSTNAME");

            entity.Property(e => e.Lastname)
                .HasMaxLength(50)
                .HasColumnName("LASTNAME");

            entity.Property(e => e.Mi)
                .HasMaxLength(50)
                .HasColumnName("MI");

            entity.Property(e => e.Midterm).HasColumnName("MIDTERM");

            entity.Property(e => e.Offerno).HasColumnName("OFFERNO");

            entity.Property(e => e.Prefinal).HasColumnName("PREFINAL");

            entity.Property(e => e.Prelim).HasColumnName("PRELIM");

            entity.Property(e => e.Retake)
                .HasMaxLength(50)
                .HasColumnName("RETAKE");

            entity.Property(e => e.Semester).HasColumnName("SEMESTER");

            entity.Property(e => e.Studno).HasColumnName("STUDNO");

            entity.Property(e => e.Syr).HasColumnName("SYR");

            entity.Property(e => e.Teachid).HasColumnName("TEACHID");

            entity.Property(e => e.Time).HasColumnName("TIME");

            entity.Property(e => e.Units).HasColumnName("UNITS");

            entity.Property(e => e.Yrlevel).HasColumnName("YRLEVEL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SubmittedGrade> entity);
    }
}
